### ISSUE TITLE
use envsubst to resolve env before passing envoy.yaml file to envoy

### ISSUE THREAD

**Issue by adilhafeez** [katanemo/arch#213]
similar to https://github.com/open-telemetry/opentelemetry-demo/blob/main/src/frontendproxy/Dockerfile#L11

**Comment by salmanap** [comment]
Note: please make sure we follow common convention when asking environment variables from developers. For e.g. in python its os.getenv(NAME). Docker also passes environment variables without the $ sign, and only uses that convention when it needs to retrieve environment variables locally (so that it doesn't conflict/confuse the declaration with retrieval)
